import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        style={{
          backgroundColor: "#fef4c7",
          fontFamily: "Comic Sans MS, sans-serif",
        }}
      >
        <header
          style={{
            textAlign: "center",
            padding: "20px",
            backgroundColor: "#ffd966",
          }}
        >
          <h1 style={{ color: "#6fa3ef" }}>Noite das Massinhas</h1>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
